<?php

$finder = PhpCsFixer\Finder::create();

return new PhpCsFixer\Config()
  ->setIndent('  ')
  ->setFinder($finder)
  ->setRiskyAllowed(true)
  ->setRules([
    'array_push'                                       => true,
    'ereg_to_preg'                                     => true,
    'modernize_strpos'                                 => true,
    'set_type_to_cast'                                 => true,
    'no_mixed_echo_print'                              => true,
    'pow_to_exponentiation'                            => true,
    'control_structure_braces'                         => true,
    'no_trailing_comma_in_singleline'                  => true,
    'normalize_index_brace'                            => true,
    'return_to_yield_from'                             => true,
    'trim_array_spaces'                                => true,
    'attribute_empty_parentheses'                      => true,
    'no_alias_language_construct_call'                 => true,
    'no_multiple_statements_per_line'                  => true,
    'single_line_empty_body'                           => true,
    'lowercase_keywords'                               => true,
    'no_short_bool_cast'                               => true,
    'class_attributes_separation'                      => true,
    'class_definition'                                 => true,
    'modifier_keywords'                                => true,
    'no_blank_lines_after_class_opening'               => true,
    'ordered_class_elements'                           => true,
    'ordered_interfaces'                               => true,
    'ordered_traits'                                   => true,
    'ordered_types'                                    => true,
    'self_accessor'                                    => true,
    'self_static_accessor'                             => true,
    'single_class_element_per_statement'               => true,
    'single_trait_insert_per_statement'                => true,
    'multiline_comment_opening_closing'                => true,
    'no_empty_comment'                                 => true,
    'single_line_comment_spacing'                      => true,
    'control_structure_braces'                         => true,
    'elseif'                                           => true,
    'empty_loop_body'                                  => true,
    'empty_loop_condition'                             => true,
    'include'                                          => true,
    'no_break_comment'                                 => true,
    'no_superfluous_elseif'                            => true,
    'no_unneeded_braces'                               => true,
    'no_useless_else'                                  => true,
    'simplified_if_return'                             => true,
    'switch_case_semicolon_to_colon'                   => true,
    'switch_case_space'                                => true,
    'fopen_flag_order'                                 => true,
    'fopen_flags'                                      => true,
    'function_declaration'                             => true,
    'function_typehint_space'                          => true,
    'implode_call'                                     => true,
    'lambda_not_used_import'                           => true,
    'method_argument_space'                            => true,
    'no_spaces_after_function_name'                    => true,
    'no_unreachable_default_argument_value'            => true,
    'nullable_type_declaration_for_default_null_value' => true,
    'phpdoc_to_param_type'                             => true,
    'phpdoc_to_property_type'                          => true,
    'return_type_declaration'                          => true,
    'single_line_throw'                                => true,
    'group_import'                                     => true,
    'no_unneeded_import_alias'                         => true,
    'no_unused_imports'                                => true,
    'ordered_imports'                                  => true,
    'single_line_after_imports'                        => true,
    'combine_consecutive_issets'                       => true,
    'combine_consecutive_unsets'                       => true,
    'dir_constant'                                     => true,
    'error_suppression'                                => true,
    'explicit_indirect_variable'                       => true,
    'function_to_constant'                             => true,
    'get_class_to_class_keyword'                       => true,
    'is_null'                                          => true,
    'no_unset_on_property'                             => true,
    'nullable_type_declaration'                        => true,
    'single_space_after_construct'                     => true,
    'list_syntax'                                      => true,
    'blank_line_after_namespace'                       => true,
    'blank_lines_before_namespace'                     => true,
    'clean_namespace'                                  => true,
    'no_leading_namespace_whitespace'                  => true,
    'concat_space'                                     => true,
    'increment_style'                                  => true,
    'logical_operators'                                => true,
    'long_to_shorthand_operator'                       => true,
    'new_expression_parentheses'                       => true,
    'new_with_braces'                                  => true,
    'no_space_around_double_colon'                     => true,
    'no_useless_concat_operator'                       => true,
    'no_useless_nullsafe_operator'                     => true,
    'object_operator_without_whitespace'               => true,
    'standardize_increment'                            => true,
    'standardize_not_equals'                           => true,
    'ternary_operator_spaces'                          => true,
    'ternary_to_null_coalescing'                       => true,
    'unary_operator_spaces'                            => true,
    'blank_line_after_opening_tag'                     => true,
    'no_closing_tag'                                   => true,
    'align_multiline_comment'                          => true,
    'no_blank_lines_after_phpdoc'                      => true,
    'no_empty_phpdoc'                                  => true,
    'no_superfluous_phpdoc_tags'                       => true,
    'phpdoc_add_missing_param_annotation'              => true,
    'phpdoc_align'                                     => true,
    'phpdoc_annotation_without_dot'                    => true,
    'phpdoc_indent'                                    => true,
    'phpdoc_inline_tag_normalizer'                     => true,
    'phpdoc_no_useless_inheritdoc'                     => true,
    'phpdoc_order_by_value'                            => true,
    'phpdoc_param_order'                               => true,
    'phpdoc_return_self_reference'                     => true,
    'phpdoc_scalar'                                    => true,
    'phpdoc_trim'                                      => true,
    'no_useless_return'                                => true,
    'return_assignment'                                => true,
    'simplified_null_return'                           => true,
    'multiline_whitespace_before_semicolons'           => true,
    'no_empty_statement'                               => true,
    'no_singleline_whitespace_before_semicolons'       => true,
    'semicolon_after_instruction'                      => true,
    'space_after_semicolon'                            => true,
    'strict_comparison'                                => true,
    'strict_param'                                     => true,
    'escape_implicit_backslashes'                      => true,
    'explicit_string_variable'                         => true,
    'simple_to_complex_string_variable'                => true,
    'single_quote'                                     => true,
    'string_length_to_empty'                           => true,
    'blank_line_before_statement'                      => true,
    'blank_line_between_import_groups'                 => true,
    'compact_nullable_type_declaration'                => true,
    'compact_nullable_typehint'                        => true,
    'heredoc_indentation'                              => true,
    'indentation_type'                                 => true,
    'line_ending'                                      => true,
    'method_chaining_indentation'                      => true,
    'no_extra_blank_lines'                             => true,
    'array_indentation'                                => true,
    'use_arrow_functions'                              => true,
    'void_return'                                      => true,
    'no_spaces_around_offset'                          => true,
    'no_spaces_inside_parenthesis'                     => true,
    'no_trailing_whitespace'                           => true,
    'no_whitespace_in_blank_line'                      => true,
    'single_blank_line_at_eof'                         => true,
    'statement_indentation'                            => true,
    'type_declaration_spaces'                          => true,
    'lowercase_static_reference'                       => true,
    'magic_constant_casing'                            => true,
    'magic_method_casing'                              => true,
    'native_function_casing'                           => true,
    'native_type_declaration_casing'                   => true,
    'class_reference_name_casing'                      => true,
    'no_multiline_whitespace_around_double_arrow'      => true,
    'trailing_comma_in_multiline'                      => false,
    'psr_autoloading'                                  => ['dir' => null],
    'constant_case'                                    => ['case' => 'lower'],
    'array_syntax'                                     => ['syntax' => 'short'],
    'cast_spaces'                                      => ['space' => 'single'],
    'types_spaces'                                     => ['space' => 'single'],
    'ordered_attributes'                               => ['sort_algorithm' => 'alpha'],
    'numeric_literal_separator'                        => ['strategy' => 'use_separator'],
    'whitespace_after_comma_in_array'                  => ['ensure_single_space' => true],
    'binary_operator_spaces'                           => [
      'default'   => 'single_space',
      'operators' => ['=>' => 'align_single_space_minimal']
    ],
    'braces_position' => [
      'functions_opening_brace'           => 'same_line',
      'classes_opening_brace'             => 'same_line',
      'control_structures_opening_brace'  => 'same_line',
      'anonymous_functions_opening_brace' => 'same_line',
      'anonymous_classes_opening_brace'   => 'same_line'
    ],
  ]);
